### PR TITLE
Default preferences

### PR DESCRIPTION
**Pull request by janbina**
Hi,

I am dealing with an old project, which is using getDefaultSharedPreferences() instead of getSharedPreferences(name, mode). I want to start using this library in it, as I am using it in all projects, but there is currently no way to use default shared preferences file.

I think there should be such an option, so I created this PR. What do you think?

### CODE REVIEW

**Comment by noties** [comment]
Hey! I will check the pull-request, thanks! 

Meanwhile, I want to mention that there are few ways to deal with default shared preferences:
* https://stackoverflow.com/a/26675526 (we can easily access the raw file, there is no magic)
* and, we could _mock_ the context with`ContextWrapper`, override the `getSharedPreferences` method and return desired SharedPreferences instance

**Comment by noties** [comment]
Pull request look good! 👍 

I just want to discuss, maybe having an option in `@SPGPreference` which will generate a constructor with raw `SharedPreferences` instance might be better? This way we might be future-proof from possible different use-cases (for example, new modes that might appear in a future Android SDK release). For me it feels more natural

**Comment by janbina** [comment]
This is a good idea. So instead of that `boolean` parameter in `@SPGPreference`, you would put there `integer` param and define constants for it (only one for now)?

**Comment by noties** [comment]
No, I must have said it wrong. I mean, to add an option for generated class to have `(SharedPreferences preferences)` constructor instead of `(Context context, int mode)`... But it renders the `preferenceName` option useless... And of cause the `singleton` one. So... Now I think that in order to keep things simple, it might be better just to merge :) If you don't have any objections, of cause XD

**Comment by janbina** [comment]
Oh, I see. This isn't bad idea either, I actually quite like it. `preferenceName` will be useless, but with my solution it is useless as well. `singleton` could be usable, if we add something like `SharedPreferencesProvider`, or there could be `init(Context)` and `init(SharedPreferences)` static methods directly in the preferences class.

**Comment by janbina** [comment]
But if you want to keep it simple, go ahead and just merge it.

**Comment by noties** [comment]
Sorry for some delay from my side. Merging for now

**Pull request merged**
